# Generated by Django 4.2 on 2026-04-05 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('blacklisted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'blacklisted_tokens',
            },
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['token'], name='blacklisted_token_d070ae_idx'),
        ),
    ]
