# Generated by Django 4.2 on 2026-04-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blacklistedtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'Superadmin')], default='USER', max_length=20),
        ),
    ]
